resource_group_name     ="kml_rg_main-c41d078df6ac415a"
resource_group_location = "West US"
storage_account         = "storageforbackendtf90"
azure_key_vault         = "azkrekv1987"
virtual_network_name    = "pythonloginappnet"
subnet_name             = "pythonloginappsub"
network_security_group  = "pythonloginappsg"
public_ip_name          = "pyhonloginapppub"
network_interface_name  = "pyhonloginappnic"
aks_cluster_name        = "pythonloginappaks"

